//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KitsTajmMobile.Strings {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Week {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Week() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KitsTajmMobile.Strings.Week", typeof(Week).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitet.
        /// </summary>
        internal static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fre
        ///{0:dd/MM}.
        /// </summary>
        internal static string FridayFormat {
            get {
                return ResourceManager.GetString("FridayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mån
        ///{0:dd/MM}.
        /// </summary>
        internal static string MondayFormat {
            get {
                return ResourceManager.GetString("MondayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Januari.
        /// </summary>
        internal static string Month1 {
            get {
                return ResourceManager.GetString("Month1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oktober.
        /// </summary>
        internal static string Month10 {
            get {
                return ResourceManager.GetString("Month10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to November.
        /// </summary>
        internal static string Month11 {
            get {
                return ResourceManager.GetString("Month11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to December.
        /// </summary>
        internal static string Month12 {
            get {
                return ResourceManager.GetString("Month12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Februari.
        /// </summary>
        internal static string Month2 {
            get {
                return ResourceManager.GetString("Month2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mars.
        /// </summary>
        internal static string Month3 {
            get {
                return ResourceManager.GetString("Month3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April.
        /// </summary>
        internal static string Month4 {
            get {
                return ResourceManager.GetString("Month4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maj.
        /// </summary>
        internal static string Month5 {
            get {
                return ResourceManager.GetString("Month5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juni.
        /// </summary>
        internal static string Month6 {
            get {
                return ResourceManager.GetString("Month6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Juli.
        /// </summary>
        internal static string Month7 {
            get {
                return ResourceManager.GetString("Month7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Augusti.
        /// </summary>
        internal static string Month8 {
            get {
                return ResourceManager.GetString("Month8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to September.
        /// </summary>
        internal static string Month9 {
            get {
                return ResourceManager.GetString("Month9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lör
        ///{0:dd/MM}.
        /// </summary>
        internal static string SaturdayFormat {
            get {
                return ResourceManager.GetString("SaturdayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sön
        ///{0:dd/MM}.
        /// </summary>
        internal static string SundayFormat {
            get {
                return ResourceManager.GetString("SundayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tors
        ///{0:dd/MM}.
        /// </summary>
        internal static string ThursdayFormat {
            get {
                return ResourceManager.GetString("ThursdayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tis
        ///{0:dd/MM}.
        /// </summary>
        internal static string TuesdayFormat {
            get {
                return ResourceManager.GetString("TuesdayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ons
        ///{0:dd/MM}.
        /// </summary>
        internal static string WednesdayFormat {
            get {
                return ResourceManager.GetString("WednesdayFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vecka {0}.
        /// </summary>
        internal static string WeekFormat {
            get {
                return ResourceManager.GetString("WeekFormat", resourceCulture);
            }
        }
    }
}
